plugins {
    id 'java'
    id 'idea'
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'idea'

    group = mod_group
    version = mod_version

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = java_version as int
    }

    repositories {
        mavenCentral()
        maven { url = "https://maven.parchmentmc.org" }
    }
}
