package wd40.lubricant.buildscript;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

// Converts a Fabric .accesswidener file into a Forge/NeoForge accesstransformer.cfg.
//
// AW (slashes, separate "type" keyword):
//     accessible class  net/minecraft/world/entity/Entity
//     accessible method net/minecraft/world/entity/Entity setPos (DDD)V
//     extendable class  net/minecraft/world/entity/Entity
//     mutable    field  net/minecraft/world/entity/Entity removalReason Lnet/minecraft/...;
//
// AT (dots, no type keyword - position implies kind):
//     public        net.minecraft.world.entity.Entity
//     public        net.minecraft.world.entity.Entity setPos(DDD)V
//     public-f      net.minecraft.world.entity.Entity
//     public-f      net.minecraft.world.entity.Entity removalReason
//
// AW says "make public" via 'accessible'. 'extendable' and 'mutable' both also strip final,
// which AT expresses with the "-f" suffix.

public final class AccessWidenerToTransformerConverter {

    public static List<String> convert(Path awFile) throws IOException {
        List<String> in = Files.readAllLines(awFile);
        List<String> out = new ArrayList<>();
        out.add("# Generated by lubricant buildSrc from " + awFile.getFileName());
        out.add("# Do not edit - regenerated each build from the canonical AW file.");

        for (String raw : in) {
            String line = stripComment(raw).trim();
            if (line.isEmpty()) continue;
            if (line.startsWith("accessWidener")) continue;  // header line

            String[] parts = line.split("\\s+");
            if (parts.length < 3) continue;

            String awAccess = parts[0];                 // accessible | extendable | mutable
            String awKind   = parts[1];                 // class | method | field
            String owner    = parts[2].replace('/', '.');
            String prefix   = atPrefix(awAccess);

            switch (awKind) {
                case "class" -> out.add(prefix + " " + owner);
                case "method" -> {
                    if (parts.length < 5) continue;
                    out.add(prefix + " " + owner + " " + parts[3] + parts[4]);
                }
                case "field" -> {
                    if (parts.length < 4) continue;
                    // AT for fields ignores the descriptor.
                    out.add(prefix + " " + owner + " " + parts[3]);
                }
                default -> {} // unknown kind; ignore
            }
        }
        return out;
    }

    public static void writeAt(Path awFile, Path atFile) throws IOException {
        List<String> lines = convert(awFile);
        Files.createDirectories(atFile.getParent());
        Files.write(atFile, lines);
    }

    private static String atPrefix(String awAccess) {
        return switch (awAccess) {
            case "accessible"            -> "public";
            case "extendable", "mutable" -> "public-f"; // public + strip final
            default -> throw new IllegalArgumentException("Unknown AW access modifier: " + awAccess);
        };
    }

    private static String stripComment(String line) {
        int hash = line.indexOf('#');
        return hash < 0 ? line : line.substring(0, hash);
    }

    private AccessWidenerToTransformerConverter() {}
}
