package wd40.lubricant.api.common.net;

import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.resources.ResourceLocation;
import wd40.lubricant.api.client.net.handlers.ClientHandler;
import wd40.lubricant.api.server.net.handlers.ServerHandler;
import wd40.lubricant.core.net.AutoCodec;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;

/**
 * Per-mod factory for network payload registration.
 *
 * <pre>{@code
 * private static final Payloads PAYLOADS = Payloads.create(MyMod.ID);
 *
 * public record HelloPayload(int tick) implements CustomPacketPayload {
 *     public static final Type<HelloPayload> TYPE = PAYLOADS.type("hello");
 *     @Override public Type<HelloPayload> type() { return TYPE; }
 * }
 *
 * public static final S2CPayload<HelloPayload> HELLO = PAYLOADS.toClient(
 *     HelloPayload.class, (payload, ctx) -> ...);
 * }</pre>
 *
 * <p>The codec is auto-derived from the record's components. To override (custom
 * field types, versioning, etc.) declare a {@code public static final
 * StreamCodec<RegistryFriendlyByteBuf, T> CODEC} field on the record - lubricant
 * detects it and uses it instead of the autogenerated one.</p>
 */
public final class Payloads {

    private final String modId;

    private Payloads(String modId) {
        this.modId = modId;
    }

    public static Payloads create(String modId) {
        return new Payloads(modId);
    }

    /** Build a {@link CustomPacketPayload.Type} under this factory's modid. */
    public <T extends CustomPacketPayload> CustomPacketPayload.Type<T> type(String path) {
        return new CustomPacketPayload.Type<>(ResourceLocation.fromNamespaceAndPath(modId, path));
    }

    /**
     * Register an S2C payload. Reads the {@code TYPE} field from {@code recordClass},
     * uses its {@code CODEC} field if present otherwise autogenerates one from record
     * components, registers with vanilla, wires the handler, returns a typed send-helper.
     */
    public <T extends CustomPacketPayload> S2CPayload<T> toClient(
            Class<T> recordClass, ClientHandler<T> handler) {
        return Net.toClient(typeOf(recordClass), codecOf(recordClass), handler);
    }

    /** Same as {@link #toClient} but for client -> server. */
    public <T extends CustomPacketPayload> C2SPayload<T> toServer(
            Class<T> recordClass, ServerHandler<T> handler) {
        return Net.toServer(typeOf(recordClass), codecOf(recordClass), handler);
    }

    @SuppressWarnings("unchecked")
    private static <T extends CustomPacketPayload> CustomPacketPayload.Type<T> typeOf(Class<T> cls) {
        try {
            Field field = cls.getDeclaredField("TYPE");
            if (!Modifier.isStatic(field.getModifiers())) {
                throw new IllegalStateException(cls.getName() + ".TYPE must be static");
            }
            field.setAccessible(true);
            Object value = field.get(null);
            if (!(value instanceof CustomPacketPayload.Type<?> type)) {
                throw new IllegalStateException(cls.getName() + ".TYPE must be a CustomPacketPayload.Type");
            }
            return (CustomPacketPayload.Type<T>) type;
        } catch (NoSuchFieldException e) {
            throw new IllegalStateException(cls.getName() + " has no TYPE field - declare " +
                    "public static final Type<" + cls.getSimpleName() + "> TYPE = PAYLOADS.type(\"...\");", e);
        } catch (IllegalAccessException e) {
            throw new IllegalStateException("can't read " + cls.getName() + ".TYPE", e);
        }
    }

    @SuppressWarnings("unchecked")
    private static <T extends CustomPacketPayload> StreamCodec<RegistryFriendlyByteBuf, T> codecOf(Class<T> cls) {
        try {
            Field field = cls.getDeclaredField("CODEC");
            if (Modifier.isStatic(field.getModifiers())) {
                field.setAccessible(true);
                return (StreamCodec<RegistryFriendlyByteBuf, T>) field.get(null);
            }
        } catch (NoSuchFieldException ignored) {
            // fall through to autogen
        } catch (IllegalAccessException e) {
            throw new IllegalStateException("can't read " + cls.getName() + ".CODEC", e);
        }
        return AutoCodec.forRecord(cls);
    }
}
