modLoader = "javafml"
loaderVersion = "[52,)"
license = "MIT"

[[mods]]
modId = "cog"
version = "1.0.0"
displayName = "Cog"
authors = "vaakx"
description = '''Example mod for the Lubricant platform.'''

[[dependencies.cog]]
    modId = "forge"
    mandatory = true
    versionRange = "[52,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cog]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.21.1]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cog]]
    modId = "lubricant"
    mandatory = true
    versionRange = "[1.0.0,)"
    ordering = "AFTER"
    side = "BOTH"
